// The only numbers the kits and posts may state about traction, each with where it comes from.
// data/leaderboard.json is a snapshot of what onchain/indexer rebuilt from Base Sepolia and Solana
// devnet (no office, no keys); the deployment records name what was deployed and run on devnet.
// data/counts.json is made from those files alone, so it can be checked without a network:
//
//   npx tsx launch/chain/tools/counts.ts                       rewrite data/counts.json
//   npx tsx launch/chain/tools/counts.ts --check               exit 1 if it is stale (npm test runs this too)
//   npx tsx launch/chain/tools/counts.ts --refresh <out dir>   first copy leaderboard.json from an indexer run
//
// To refresh the snapshot: cd onchain/indexer && npm run index -- --network base-sepolia --out out/
// then run this with --refresh onchain/indexer/out.

import { copyFileSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { isMain, LAUNCH_DIR, REPO_DIR } from './calendar.js';

interface Row {
  key: string;
  merged: number;
  selfMerged: number;
  reverted: number;
  closedUnmerged: number;
  distinctMaintainers: number;
}

interface Board {
  window: string;
  by: 'harness' | 'agent';
  rows: Row[];
}

export interface Leaderboard {
  schema: string;
  asOf: number;
  boards: Board[];
}

export interface DevnetRecord {
  cluster: string;
  programId: string;
  e2e?: { amount: string; signatures: Record<string, string> }[];
}

export interface CountsFile {
  note: string;
  asOf: string;
  sources: Record<string, string>;
  counts: Record<string, number>;
}

const SOURCES = {
  leaderboard: 'launch/chain/data/leaderboard.json (onchain/indexer, Base Sepolia attestations and Solana devnet payouts)',
  devnet: 'onchain/solana/deployments/devnet.json',
};

function sum(rows: Row[], pick: (r: Row) => number): number {
  return rows.reduce((n, r) => n + pick(r), 0);
}

/** Every count, from the leaderboard snapshot and the devnet deployment record. */
export function countsFrom(board: Leaderboard, devnet: DevnetRecord): CountsFile {
  if (board.schema !== 'agent-office/proof-of-merge-leaderboard@1') throw new Error(`unknown leaderboard schema "${board.schema}"`);
  if (devnet.cluster !== 'devnet') throw new Error(`the devnet record is for "${devnet.cluster}"`);
  const all = (by: Board['by']) => board.boards.find((b) => b.window === 'all' && b.by === by)?.rows ?? [];
  const harness = all('harness');
  const runs = devnet.e2e ?? [];
  return {
    note: 'Generated by launch/chain/tools/counts.ts. Do not edit by hand: the linter only lets a sourced field state these numbers.',
    asOf: new Date(board.asOf * 1000).toISOString(),
    sources: {
      merged_by_others: SOURCES.leaderboard,
      self_merges: SOURCES.leaderboard,
      reverts: SOURCES.leaderboard,
      closed_unmerged: SOURCES.leaderboard,
      agents_ranked: SOURCES.leaderboard,
      harnesses_ranked: SOURCES.leaderboard,
      devnet_bounties_released: SOURCES.devnet,
      devnet_test_usdc_released: SOURCES.devnet,
    },
    counts: {
      merged_by_others: sum(harness, (r) => r.merged),
      self_merges: sum(harness, (r) => r.selfMerged),
      reverts: sum(harness, (r) => r.reverted),
      closed_unmerged: sum(harness, (r) => r.closedUnmerged),
      agents_ranked: all('agent').length,
      harnesses_ranked: harness.length,
      devnet_bounties_released: runs.filter((r) => r.signatures.release).length,
      devnet_test_usdc_released: runs.filter((r) => r.signatures.release).reduce((n, r) => n + Number(r.amount), 0),
    },
  };
}

export function render(dir = LAUNCH_DIR, repo = REPO_DIR): string {
  const board = JSON.parse(readFileSync(path.join(dir, 'data', 'leaderboard.json'), 'utf8')) as Leaderboard;
  const devnet = JSON.parse(readFileSync(path.join(repo, 'onchain', 'solana', 'deployments', 'devnet.json'), 'utf8')) as DevnetRecord;
  return JSON.stringify(countsFrom(board, devnet), null, 2) + '\n';
}

if (isMain(import.meta.url)) {
  const args = process.argv.slice(2);
  const from = args.includes('--refresh') ? args[args.indexOf('--refresh') + 1] : undefined;
  if (from) copyFileSync(path.join(path.resolve(from), 'leaderboard.json'), path.join(LAUNCH_DIR, 'data', 'leaderboard.json'));
  const file = path.join(LAUNCH_DIR, 'data', 'counts.json');
  const want = render();
  let have = '';
  try {
    have = readFileSync(file, 'utf8');
  } catch {}
  if (args.includes('--check')) {
    if (have !== want) {
      console.error('stale: data/counts.json (run: npx tsx launch/chain/tools/counts.ts)');
      process.exit(1);
    }
    console.log('counts up to date');
  } else {
    writeFileSync(file, want);
    console.log(have === want ? 'counts up to date' : 'wrote data/counts.json');
  }
}
